version: "3.7"

services:
  mysql3:
    image: "mysql:8.0"  # Use a stable MySQL image
    container_name: mysql3
    restart: always
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tu123  # Set a root password for MySQL
      MYSQL_DATABASE: magnusDB  # (Optional) Create a default database
      MYSQL_USER: tu          # (Optional) Create a user other than root
    volumes:
      - mssqlvolume:/var/lib/mysql  # MySQL's default data directorys
    ports:
      - "3307:3306"  # Expose MySQL on the default port 3306

volumes:
  mssqlvolume:
    name: sqlserver-xtlab-vl